### ISSUE TITLE
Test failing during pip install as a dependency of pynacl==1.5.0 on arm64/apple m1 image building

### ISSUE THREAD

**Issue by BeOleg** [jedisct1/libsodium#1302]
traceback 
```
#0 270.3       Testsuite summary for libsodium 1.0.16
#0 270.3       ============================================================================
#0 270.3       # TOTAL: 72
#0 270.3       # PASS:  71
#0 270.3       # SKIP:  0
#0 270.3       # XFAIL: 0
#0 270.3       # FAIL:  1
#0 270.3       # XPASS: 0
#0 270.3       # ERROR: 0
#0 270.3       ============================================================================
#0 270.3       See test/default/test-suite.log
#0 270.3       Please report to https://github.com/jedisct1/libsodium/issues
#0 270.3       ============================================================================
#0 270.3       make[4]: *** [Makefile:1805: test-suite.log] Error 1
#0 270.3       make[4]: Leaving directory '/tmp/pip-install-8jkckw96/pynacl_9aa19603b26d45e8932b2f90062e6064/build/temp.linux-aarch64-cpython-311/test/default'
#0 270.3       make[3]: *** [Makefile:1913: check-TESTS] Error 2
#0 270.3       make[3]: Leaving directory '/tmp/pip-install-8jkckw96/pynacl_9aa19603b26d45e8932b2f90062e6064/build/temp.linux-aarch64-cpython-311/test/default'
#0 270.3       make[2]: *** [Makefile:2481: check-am] Error 2
#0 270.3       make[2]: Leaving directory '/tmp/pip-install-8jkckw96/pynacl_9aa19603b26d45e8932b2f90062e6064/build/temp.linux-aarch64-cpython-311/test/default'
#0 270.3       make[1]: *** [Makefile:402: check-recursive] Error 1
#0 270.3       make[1]: Leaving directory '/tmp/pip-install-8jkckw96/pynacl_9aa19603b26d45e8932b2f90062e6064/build/temp.linux-aarch64-cpython-311/test'
#0 270.3       make: *** [Makefile:515: check-recursive] Error 1
#0 270.3       Traceback (most recent call last):
#0 270.3         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 270.3           main()
#0 270.3         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 270.3           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 270.3                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 270.3         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
#0 270.3           return _build_backend().build_wheel(wheel_directory, config_settings,
#0 270.3                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
#0 270.3           return self._build_with_temp_dir(
#0 270.3                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
#0 270.3           self.run_setup()
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
#0 270.3           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
#0 270.3           exec(code, locals())
#0 270.3         File "<string>", line 208, in <module>
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
#0 270.3           return distutils.core.setup(**attrs)
#0 270.3                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 270.3           return run_commands(dist)
#0 270.3                  ^^^^^^^^^^^^^^^^^^
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 270.3           dist.run_commands()
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 270.3           self.run_command(cmd)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
#0 270.3           super().run_command(command)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 270.3           cmd_obj.run()
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
#0 270.3           self.run_command("build")
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 270.3           self.distribution.run_command(command)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
#0 270.3           super().run_command(command)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 270.3           cmd_obj.run()
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
#0 270.3           self.run_command(cmd_name)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 270.3           self.distribution.run_command(command)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
#0 270.3           super().run_command(command)
#0 270.3         File "/tmp/pip-build-env-hmz70e_s/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 270.3           cmd_obj.run()
#0 270.3         File "<string>", line 179, in run
#0 270.3         File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
#0 270.3           raise CalledProcessError(retcode, cmd)
#0 270.3       subprocess.CalledProcessError: Command '['make', 'check']' returned non-zero exit status 2.
#0 270.3       [end of output]
#0 270.3   
#0 270.3   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 270.3   ERROR: Failed building wheel for pynacl
#0 270.6   Building wheel for python-card-me (setup.py): finished with status 'done'
#0 270.6   Created wheel for python-card-me: filename=python_card_me-0.9.3-py3-none-any.whl size=42220 sha256=b3d0d812a3e8ef54bd705e3d0ed7791127cf16c6823dcfdfe94601db11c7e425
#0 270.6   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/f1/ce/9a/2acc54f88998b0f6a42e9c3ffbae73ded6811bbaffc75ac7f2
#0 270.6   Building wheel for surlex (setup.py): started
#0 270.7   Building wheel for surlex (setup.py): finished with status 'done'
#0 270.7   Created wheel for surlex: filename=surlex-0.2.0-py3-none-any.whl size=5032 sha256=f9dab7705f044aa7eeb0ba99e695aaae53793520a672642aa9f3655ca2d1dbfc
#0 270.7   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/d8/10/b3/c742c31f0eb23788dc7b174540ae56b08aa6c2de21647ce1f5
#0 270.7   Building wheel for unicodecsv (setup.py): started
#0 270.9   Building wheel for unicodecsv (setup.py): finished with status 'done'
#0 270.9   Created wheel for unicodecsv: filename=unicodecsv-0.14.1-py3-none-any.whl size=10745 sha256=d0ddeedebec7a8ccac7a795b510845478a5101b28fbb40266c723a66f1b12e40
#0 270.9   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/ec/03/6f/d2e0162d94c0d451556fa43dd4d5531457245c34a36b41ef4a
#0 270.9   Building wheel for websockets (setup.py): started
#0 271.3   Building wheel for websockets (setup.py): finished with status 'done'
#0 271.3   Created wheel for websockets: filename=websockets-9.1-cp311-cp311-linux_aarch64.whl size=97249 sha256=e2578cf1aec84b5447be37b0ef9f7d16f14ec87f92719d6bd7305ed5e6b3585e
#0 271.3   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/0f/ac/ab/443aab8a24785bb249799401c27f235dc6f97d98eb15e4b684
#0 271.4   Building wheel for varint (setup.py): started
#0 271.5   Building wheel for varint (setup.py): finished with status 'done'
#0 271.5   Created wheel for varint: filename=varint-1.0.2-py3-none-any.whl size=1962 sha256=79493a9a1060192d11dcfa72726d6264eb2cb1f3bdb732362484b7e85d2fc59b
#0 271.5   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/8c/2a/c3/b16b19aae158e87add6030af381648d7ba2ba6bd4049b4a6b1
#0 271.5   Building wheel for wmctrl (setup.py): started
#0 271.7   Building wheel for wmctrl (setup.py): finished with status 'done'
#0 271.7   Created wheel for wmctrl: filename=wmctrl-0.4-py3-none-any.whl size=3839 sha256=ab563557340d1104a2dd381afbc20293e678d0d68627b30a29109be9092853d1
#0 271.7   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/3a/94/a4/03b9f05cf8022e7d3bfdb31f2f0ae6b304806ddc6e12dc0cdd
#0 271.7   Building wheel for parsimonious (setup.py): started
#0 271.9   Building wheel for parsimonious (setup.py): finished with status 'done'
#0 271.9   Created wheel for parsimonious: filename=parsimonious-0.8.1-py3-none-any.whl size=42707 sha256=c2f2e865c989efab455c14489ba36e42f5cbe0ac90e52cb9a11826fc9ff71d00
#0 271.9   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/27/54/4b/fec2bf1cb1623aca5d14d1b1477e4f9ec661e04335b3f22343
#0 271.9   Building wheel for pyrepl (setup.py): started
#0 272.1   Building wheel for pyrepl (setup.py): finished with status 'done'
#0 272.1   Created wheel for pyrepl: filename=pyrepl-0.9.0-py3-none-any.whl size=59907 sha256=5e88741ede6dc8f1265fb91df7ece86a682abb5d79c5e90d510f8656a8dd7db7
#0 272.1   Stored in directory: /tmp/pip-ephem-wheel-cache-4e7w4qxj/wheels/5d/63/d0/9abf1bc808afeedd0a80e1b107e4516f96e79a11eb4e894944
#0 272.1 Successfully built ipdb newrelic psycopg2 django-session-security python-bitcoinrpc pillow tornado dredd-hooks pdbpp django-post-office django-intercom simplejson retrying django-admin-multiple-choice-list-filter celery-once pycountry cbor lxml uphold django-loginurl python-bittrex django-audit-log stellar-sdk stellar-base-sseclient orderbook ripple-python monero django-admin-comments crc16 jwcrypto ldif3 python-card-me surlex unicodecsv websockets varint wmctrl parsimonious pyrepl
#0 272.1 Failed to build pynacl
#0 272.1 ERROR: Could not build wheels for pynacl, which is required to install pyproject.toml-based projects
#0 272.4 
#0 272.4 [notice] A new release of pip is available: 23.1.2 -> 23.2.1
#0 272.4 [notice] To update, run: pip install --upgrade pip
```

As per [StackOverflow](https://stackoverflow.com/questions/76514240/lib-sodium-pynacl-errors-while-building-arm64-python-images-for-python-django)  but this error persists.

How to solve this?

Is a specific version of libsodium required as well?

**Comment by jedisct1** [comment]
`libsodium 1.0.16` is very old. The Apple M1 didn't even exist back then.

Looking at the PyNaCl documentation, it looks like version 1.5.0 is using `libsodium 1.0.18-stable`.

That doesn't match the output you printed. So it's likely that there's something wrong in your project or in the commands you typed, and it's actually not trying to use PyNaCl 1.5.0.

The [PyNaCl documentation](https://pypi.org/project/PyNaCl/) also mentions that it can used a system installation of `libsodium`. So you can install `libsodium` with Homebrew and run the command they document: `SODIUM_INSTALL=system pip install pynacl`.

PyNaCl is a different project, maintained independently. So, in order to get help with it, questions should rather be sent to the relevant repository. This one is for `libsodium` itself.
