### ISSUE TITLE
sodium_utils2 and sodium_utils3 test fails when compiled with afl-clang-fast and address sanitizer

### ISSUE THREAD

**Issue by geeknik** [jedisct1/libsodium#493]
Hi Frank! Thought I'd take a look at libsodium this evening. (; 

Compiled with afl-clang-fast and address sanitizer like so:
`CC=afl-clang-fast AFL_USE_ASAN=1 make`
`CC=afl-clang-fast AFL_USE_ASAN=1 make check`

Which results in this:
```
===================================================
   libsodium 1.0.12: test/default/test-suite.log
===================================================

# TOTAL: 63
# PASS:  61
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: sodium_utils2
===================

ASAN:SIGSEGV
=================================================================
==5819==ERROR: AddressSanitizer: SEGV on unknown address 0x7f1b24307000 (pc 0x7f1b22fa96f6 bp 0x7ffe39099810 sp 0x7ffe39098fa8 T0)
    #0 0x7f1b22fa96f5 in memset /build/glibc-qK83Be/glibc-2.19/string/../sysdeps/x86_64/memset.S:109
    #1 0x7f1b240c02db in __asan_memset (/root/libsodium/test/default/sodium_utils2+0x8e2db)
    #2 0x7f1b240f8c33 in _sodium_memzero_as_a_weak_symbol_to_prevent_lto /root/libsodium/src/libsodium/sodium/utils.c:69:9
    #3 0x7f1b240f4f0f in xmain /root/libsodium/test/default/sodium_utils2.c:83:5
    #4 0x7f1b240f4b3a in main /root/libsodium/test/default/./cmptest.h:48:9
    #5 0x7f1b22f45b44 in __libc_start_main /build/glibc-qK83Be/glibc-2.19/csu/libc-start.c:287
    #6 0x7f1b240f499c in _start (/root/libsodium/test/default/sodium_utils2+0xc299c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-qK83Be/glibc-2.19/string/../sysdeps/x86_64/memset.S:109 memset
==5819==ABORTING

FAIL: sodium_utils3
===================

ASAN:SIGSEGV
=================================================================
==5826==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000016c2 (pc 0x7fa3eb7e975b bp 0x000000000077 sp 0x7ffe93685618 T0)
    #0 0x7fa3eb7e975a in raise /build/glibc-qK83Be/glibc-2.19/nptl/../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
    #1 0x7fa3ebce05a8 in _out_of_bounds /root/libsodium/src/libsodium/sodium/utils.c:464:5
    #2 0x7fa3ebce05a8 in sodium_free /root/libsodium/src/libsodium/sodium/utils.c:636
    #3 0x7fa3ebcdcd28 in xmain /root/libsodium/test/default/sodium_utils3.c:55:5
    #4 0x7fa3ebcdcb3a in main /root/libsodium/test/default/./cmptest.h:48:9
    #5 0x7fa3eab2db44 in __libc_start_main /build/glibc-qK83Be/glibc-2.19/csu/libc-start.c:287
    #6 0x7fa3ebcdc99c in _start (/root/libsodium/test/default/sodium_utils3+0xc299c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-qK83Be/glibc-2.19/nptl/../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37 raise
==5826==ABORTING
```

**Comment by geeknik** [comment]
I'm a dunce.
