### ISSUE TITLE
FAIL: pwhash_scrypt on s390x

### ISSUE THREAD

**Issue by james-crowley** [jedisct1/libsodium#749]
I am trying to install PyNaCl on s390x, as it is a dependency for a couple of packages in AWX. Inside my Dockerfile, I install the requirements for AWX and when running the install I see:

```
Collecting pynacl>=1.0.1 (from paramiko==2.4.0->-r /dev/stdin (line 71))
  Using cached https://files.pythonhosted.org/packages/08/19/cf56e60efd122fa6d2228118a9b345455b13ffe16a14be81d025b03b261f/PyNaCl-1.2.1.tar.gz
Skipping bdist_wheel for cffi, due to binaries being disabled for it.
Skipping bdist_wheel for pycparser, due to binaries being disabled for it.
Building wheels for collected packages: applicationinsights, backports.ssl-match-hostname, bcrypt, cryptography, deprecation, dogpile.cache, ipaddress, lxml, munch, netifaces, oauthlib, ovirt-engine-sdk-python, psphere, psutil, pycurl, pykerberos, pyyaml, secretstorage, suds, pynacl
  Running setup.py bdist_wheel for applicationinsights: started
  Running setup.py bdist_wheel for applicationinsights: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/6e/dd/75/a7b2490cb8ac7ac2b4d08c2a1e73328892c57cfc11c206b15e
  Running setup.py bdist_wheel for backports.ssl-match-hostname: started
  Running setup.py bdist_wheel for backports.ssl-match-hostname: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/99/7e/f7/a88a9bcf7a3bd6b12cf6a74eee8c89746aaa02f71ab7b33939
  Running setup.py bdist_wheel for bcrypt: started
  Running setup.py bdist_wheel for bcrypt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4a/80/07/163d01f8b5d52ed815960b532dd7aece342bccbeb2b47361fd
  Running setup.py bdist_wheel for cryptography: started
  Running setup.py bdist_wheel for cryptography: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/11/f1/29/e2d79ac972f25e42e2d480fee56c1e04b7d72a1fc3d98b142c
  Running setup.py bdist_wheel for deprecation: started
  Running setup.py bdist_wheel for deprecation: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c5/5e/5b/d5f2a555b9ea894388984faa5c8e057b92aa251859d9a9260e
  Running setup.py bdist_wheel for dogpile.cache: started
  Running setup.py bdist_wheel for dogpile.cache: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/80/00/84/7520e35df8679ed0f43c460d44a810214d4b23e298fc4aae12
  Running setup.py bdist_wheel for ipaddress: started
  Running setup.py bdist_wheel for ipaddress: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4f/fe/3e/a310b86575d8d3ce870a9c04a00a91df3c041d3e70529b4361
  Running setup.py bdist_wheel for lxml: started
  Running setup.py bdist_wheel for lxml: still running...
  Running setup.py bdist_wheel for lxml: still running...
  Running setup.py bdist_wheel for lxml: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/24/22/69/21c491640deac58adc3ee6e4efecd4ea30224e16dfd7b5f298
  Running setup.py bdist_wheel for munch: started
  Running setup.py bdist_wheel for munch: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/25/f8/67/28796da0ad96bf36eaab7ee2c8c16c58e1ba48a88b82420899
  Running setup.py bdist_wheel for netifaces: started
  Running setup.py bdist_wheel for netifaces: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a9/dc/b4/ed4577d960811e37fde4718b2b615da8e3352bd54c23731622
  Running setup.py bdist_wheel for oauthlib: started
  Running setup.py bdist_wheel for oauthlib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/58/25/10/2bda0e8ff6207967e7d0dc2c183581a93170af5ffc608d4d84
  Running setup.py bdist_wheel for ovirt-engine-sdk-python: started
  Running setup.py bdist_wheel for ovirt-engine-sdk-python: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/08/a1/b6/c5949e6ed7d50ffc4ab088a6b15084b9f1e775a1c767ff27e9
  Running setup.py bdist_wheel for psphere: started
  Running setup.py bdist_wheel for psphere: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/49/85/aa/11f5003a6dd72e0de03a7cfb76349dbf6aa48b46ec4ff10c2d
  Running setup.py bdist_wheel for psutil: started
  Running setup.py bdist_wheel for psutil: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/fe/33/84/baea3d665de2d1af7e8f827f3883811bba5e4149443ccf8191
  Running setup.py bdist_wheel for pycurl: started
  Running setup.py bdist_wheel for pycurl: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/77/c8/b6/bed2606b4ae3cf738c99c111d88ce33d8ae82171c40cbddbf0
  Running setup.py bdist_wheel for pykerberos: started
  Running setup.py bdist_wheel for pykerberos: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c7/a7/07/d414c22754acf5822ccce48b41822142974ec103057c8305e7
  Running setup.py bdist_wheel for pyyaml: started
  Running setup.py bdist_wheel for pyyaml: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/03/05/65/bdc14f2c6e09e82ae3e0f13d021e1b6b2481437ea2f207df3f
  Running setup.py bdist_wheel for secretstorage: started
  Running setup.py bdist_wheel for secretstorage: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4e/5b/1b/be8c8a830a0243af85b2946a0aece2c6743d7f7f946977ed67
  Running setup.py bdist_wheel for suds: started
  Running setup.py bdist_wheel for suds: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4b/15/96/768b567825a502ba3e308d50e531ee89911af21dec1958e2c5
  Running setup.py bdist_wheel for pynacl: started
  Running setup.py bdist_wheel for pynacl: still running...
  Running setup.py bdist_wheel for pynacl: still running...
  Running setup.py bdist_wheel for pynacl: still running...

```

Then the install just sits there. I checked the resources on my machine and I saw a process running that called **./pwhash_scrypt.** It was using about 80% to 90% of one of my cores on my server. 

From what I read, the task is pretty cpu and memory intensive. Additionally, I know it can take a while for the task to complete. 

After 30 minutes go by I checked on the task. The task was still running, and the memory utilization had increased. I watched it for a couple of minutes and the memory consumption kept increasing. 

I let the process run for about 2 hours. At the 2-hour mark, my swap was at 100% utilization and all my memory was being used by this task. Finally, after 30 more minutes, the install crashed. 

Here is the log:

```
PASS: aead_aes256gcm
PASS: aead_chacha20poly1305
PASS: aead_xchacha20poly1305
PASS: auth
PASS: auth2
PASS: auth3
PASS: auth5
PASS: auth6
PASS: auth7
PASS: box
PASS: box2
PASS: box7
PASS: box8
PASS: box_easy
PASS: box_easy2
PASS: box_seal
PASS: box_seed
PASS: chacha20
PASS: codecs
PASS: core1
PASS: core2
PASS: core3
PASS: core4
PASS: core5
PASS: core6
PASS: ed25519_convert
PASS: generichash
PASS: generichash2
PASS: generichash3
PASS: hash
PASS: hash3
PASS: kdf
PASS: keygen
PASS: kx
PASS: metamorphic
PASS: misuse
PASS: onetimeauth
PASS: onetimeauth2
PASS: onetimeauth7
PASS: pwhash_argon2i
PASS: pwhash_argon2id
PASS: randombytes
PASS: scalarmult
PASS: scalarmult2
PASS: scalarmult5
PASS: scalarmult6
PASS: scalarmult7
PASS: secretbox
PASS: secretbox2
PASS: secretbox7
PASS: secretbox8
PASS: secretbox_easy
PASS: secretbox_easy2
PASS: secretstream
PASS: shorthash
PASS: sign
PASS: sodium_core
PASS: sodium_utils
PASS: sodium_version
PASS: stream
PASS: stream2
PASS: stream3
PASS: stream4
PASS: verify1
PASS: sodium_utils2
PASS: sodium_utils3
/tmp/pip-build-JLVB5O/pynacl/src/libsodium/build-aux/test-driver: line 107: 46106 Killed                  "$@" > $log_file 2>&1
FAIL: pwhash_scrypt
PASS: pwhash_scrypt_ll
PASS: siphashx24
PASS: xchacha20
============================================================================
Testsuite summary for libsodium 1.0.15
============================================================================
# TOTAL: 70
# PASS:  69
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/default/test-suite.log
Please report to https://github.com/jedisct1/libsodium/issues
============================================================================
make[5]: *** [test-suite.log] Error 1
make[5]: Leaving directory `/tmp/pip-build-JLVB5O/pynacl/build/temp.linux-s390x-2.7/test/default'
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory `/tmp/pip-build-JLVB5O/pynacl/build/temp.linux-s390x-2.7/test/default'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/tmp/pip-build-JLVB5O/pynacl/build/temp.linux-s390x-2.7/test/default'
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory `/tmp/pip-build-JLVB5O/pynacl/build/temp.linux-s390x-2.7/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/tmp/pip-build-JLVB5O/pynacl/build/temp.linux-s390x-2.7'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-JLVB5O/pynacl/setup.py", line 251, in <module>
    "Programming Language :: Python :: 3.6",
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 202, in run
    self.run_command('build')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/pip-build-JLVB5O/pynacl/setup.py", line 179, in run
    subprocess.check_call(["make", "check"] + make_args, cwd=build_temp)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'check']' returned non-zero exit status 2

----------------------------------------
Failed building wheel for pynacl
Running setup.py clean for pynacl
Successfully built applicationinsights backports.ssl-match-hostname bcrypt cryptography deprecation dogpile.cache ipaddress lxml munch netifaces oauthlib ovirt-engine-sdk-python psphere psutil pycurl pykerberos pyyaml secretstorage suds
Failed to build pynacl

```

I did see this issue, #721, that had a similar problem. So, I followed the advice there and increased my max memory lock limit from 64 to 16384. But I still crashed with the same issue. 

My system specs are as follows:

Total Memory: 16 GB
Free Memory: 15.5 GB
Processors: 8
Arch: IBM/S390x
System OS: Ubuntu 16.04.4 LTS
Docker OS: ClefOS
Pip: 8.1.2
Python: 2.7.5

**Comment by jedisct1** [comment]
Try increasing other limits, maybe? Or better, try to find what exact test is failing, as I have no ways to reproduce this.

**Comment by james-crowley** [comment]
Thanks for the quick response. What other limits do you suggest increasing? 

As for identifying what exact test is failing, how do I go about testing/debugging that? Would I need to compile the libsodium, then run and compile pwhash_scrypt.c? 

My other question is what is the normal behavior when running pwhash_scrypt? Is it supposed to take up a lot memory and keep increasing? From looking at the test in the repo, it looks like its testing out the password hashing function? 

As for not having any way to reproduce this, one option is signing up for the LinuxONE Community Cloud which will give you access to a Linux instance hosted on a s390x platform. 

If you’re interested let me know, I can expedite process and possibly extend the 120-day trial period.

**Comment by jedisct1** [comment]
Thanks James,

How do you get Ubuntu installed on these? I registered but can only see RHES and SLES images.

**Comment by james-crowley** [comment]
Frank,

Thanks for signing up! What is your username/email that you signed up with? To get access to an Ubuntu instance you need to submit a request. Feel free to email me your info at James.Crowley@ibm.com.

**Comment by jedisct1** [comment]
`linuxone@pureftpd.org`

(and of course, it seems to work fine on a RHEL instance...)

**Comment by james-crowley** [comment]
I got RHEL to work too. I think we should go ahead a do a test on Ubuntu and make sure that it works too. I’ll notify you once I get an Ubuntu instance ready. Thank you for your patience.

The system I was having issues on was Docker pulling from a base image of ClefOS. ClefOS is a port of Centos for s390x. It is interesting that RHEL worked, since ClefOS should have similar packages. I am going to spin up a ClefOS system on bare metal instead of running it in Docker and see if that makes any difference.

**Comment by james-crowley** [comment]
@jedisct1 I am still working internally to get you access to an Ubuntu instance. But for now, if you could fill out this form, https://developer.ibm.com/linuxone/registration-ubuntu/ . That should start the process of getting access to an Ubuntu instance.

**Comment by jedisct1** [comment]
ping?

**Comment by james-crowley** [comment]
I have yet to hear back internally about getting access to an Ubuntu system. The best bet would be filling out that form linked in my previous post, that should give you access to an Ubuntu system. 

As for testing, I have found some interesting results. At first, when looking at the systems that the install was failing on, I noticed that they are all Z13 machines. To tell if it’s a Z13 vs Z14, cat /proc/sysinfo and look at “Type”. If the type is **2964** it is a Z13 and if the type is **3906** it is a Z14. 

There are many changes between the Z13 and the Z14 but one of them that might affect the install is the underlying crypto packages. I thought this might be the issue, _until_ I checked the type of the LinuxONE VM and it’s a Z13. 

So, the problem does **NOT** appear to be Z13 issue, as it can install on certain OS’s. The odd thing is the install does not work with ClefOS on Z13 but does on Z14. I have yet to verify if the install works on Ubuntu. 

Is there any way to see what’s going on a deeper level during the install? I was planning on doing a strace to get some more info back to pinpoint where in the code the systems hangs.

**Comment by jedisct1** [comment]
Hi James,

Do these instances have the same amount of RAM?

I filled out the form 2 week ago, but didn't receive any updates. Maybe you can spin up one of these and give me access to a shell on it so I can take look?

`strace` is not going to help much, as the tests do very little system calls.
