### ISSUE TITLE
Libsodium fails on OSS-Fuzz

### ISSUE THREAD

**Issue by guidovranken** [jedisct1/libsodium#859]
I noticed this because Cryptofuzz is failing as well.

backtrace is

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000005240e3 in __interceptor_getrandom () at /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:9557
#2  0x0000000000692c21 in _randombytes_linux_getrandom () at randombytes/sysrandom/randombytes_sysrandom.c:233
#3  0x0000000000692782 in randombytes_linux_getrandom () at randombytes/sysrandom/randombytes_sysrandom.c:250
#4  0x00000000006925c7 in randombytes_sysrandom_init () at randombytes/sysrandom/randombytes_sysrandom.c:270
#5  0x000000000069232a in randombytes_sysrandom_stir () at randombytes/sysrandom/randombytes_sysrandom.c:298
#6  0x0000000000641a53 in randombytes_stir () at randombytes/randombytes.c:82
#7  0x0000000000641640 in sodium_init () at sodium/core.c:40
#8  0x000000000063329c in cryptofuzz::module::libsodium::libsodium() () at module.cpp:11
#9  0x00000000005f07c1 in std::__1::__shared_ptr_emplace<cryptofuzz::module::libsodium, std::__1::allocator<cryptofuzz::module::libsodium> >::__shared_ptr_emplace(std::__1::allocator<cryptofuzz::module::libsodium>) () at /usr/local/bin/../include/c++/v1/memory:3538
#10 0x00000000005f0307 in std::__1::shared_ptr<cryptofuzz::module::libsodium> std::__1::shared_ptr<cryptofuzz::module::libsodium>::make_shared<>() () at /usr/local/bin/../include/c++/v1/memory:4202
#11 0x00000000005e9ab9 in std::__1::make_shared<cryptofuzz::module::libsodium> () at /usr/local/bin/../include/c++/v1/memory:4581
#12 0x00000000005e8fde in LLVMFuzzerInitialize () at entry.cpp:110
#13 0x000000000046b5ad in FuzzerDriver () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:615
#14 0x0000000000496c73 in main () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19
#15 0x00007ffff6ee5830 in __libc_start_main (main=0x496c50 <main>, argc=1, argv=0x7fffffffe0f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe0e8)
    at ../csu/libc-start.c:291
#16 0x0000000000440a79 in _start ()
```

Compilation of libsodium also gives a compile warning:

```
Step #4: randombytes/sysrandom/randombytes_sysrandom.c:233:18: warning: implicit declaration of function 'getrandom' is invalid in C99 [-Wimplicit-function-declaration]
Step #4:         readnb = getrandom(buf, size, 0);
Step #4:                  ^
Step #4: 1 warning generated.
Step #4: randombytes/internal/randombytes_internal_random.c:219:18: warning: implicit declaration of function 'getrandom' is invalid in C99 [-Wimplicit-function-declaration]
Step #4:         readnb = getrandom(buf, size, 0);
```

See: https://oss-fuzz-build-logs.storage.googleapis.com/log-38462662-e510-434e-b51a-29c325266d07.txt

Possibly something is wrong with your getrandom detection logic?

**Comment by jedisct1** [comment]
The version of the headers don't match the version of the linked C library.

**Comment by guidovranken** [comment]
Why? getrandom seems to be absent in both the headers (leading to the warning) and the binary (leading to the crash).

**Comment by jedisct1** [comment]
Can you put the `config.log` file somewhere?

**Comment by jedisct1** [comment]
This is a bit surprising, because if it weren't present in the library, it wouldn't link.

**Comment by guidovranken** [comment]
I'll have the config.log in a minute..

I think it links because AddressSanitizer provides an overload for getrandom? Which then calls the real getrandom, which doesn't exist.

```
#0  0x0000000000000000 in ?? ()
#1  0x00000000005240e3 in __interceptor_getrandom () at /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:9557
#2  0x0000000000692c21 in _randombytes_linux_getrandom () at randombytes/sysrandom/randombytes_sysrandom.c:233
```

**Comment by guidovranken** [comment]
config.log https://pastebin.com/rKsZPKJK

**Comment by jedisct1** [comment]
```textt
configure:19108: checking for getrandom
configure:19108: clang -o conftest -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -ftls-model=local-dynamic  -D_FORTIFY_SOURCE=2 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack conftest.c   >&5
configure:19108: $? = 0
configure:19108: result: yes
```

`getrandom()` is present, and links fine. The detection code compiles and links actual code using it.

Maybe unrelated, but where does that `-stdlib=libc++` come from?

**Comment by jedisct1** [comment]
I think ASAN assumes that the underlying library is more recent than the one installed.

**Comment by guidovranken** [comment]
The OSS-Fuzz build script provides all these flags.

Would you mind commenting in this thread? https://github.com/google/oss-fuzz/issues/2775

**Comment by jedisct1** [comment]
Can you try the `next` branch?

**Comment by jedisct1** [comment]
I don't know if this is possible, and this is likely to be unrelated, but maybe removing `-stdlib=libc++` wouldn't be a bad idea, as it may also cause unexpected functions to be defined and confuse the detection script.

**Comment by guidovranken** [comment]
next branch has the same problem. I'll try removing ```-stdlib=libc++```

**Comment by guidovranken** [comment]
Unfortunately removing ```-stdlib=libc++``` does not solve it.

**Comment by guidovranken** [comment]
When I remove -fsanitize=address from the build flags, the problem is gone. Very strange.

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium/commit/203220116aeb29f935c8c86f458ee4e51cd1b077 should have worked around it
